### ISSUE TITLE
Messages doesn't render in shared channel threads (recent regression)

### ISSUE THREAD

**Issue by flugsio** [wee-slack/wee-slack#757]
Steps to reproduce
1. Use `/thread id` from a shared channel (it seems to work correctly in regular channels)
2. no message appears, but a traceback

```
09:38 Connecting to 1 slack team.
09:38 python scripts loaded: slack
09:38 Plugins loaded: alias, buflist, charset, exec, fifo, fset, guile, irc, logger, lua, perl, python, relay, script, tcl, trigger, xfer
09:39 Connected to Slack team Promote (promoteint.slack.com) with username flugsio
09:46 python: stdout/stderr (slack): Traceback (most recent call last):
09:46 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 668, in handle_next
09:46 python: stdout/stderr (slack):     EVENTROUTER.handle_next()
09:46 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 661, in handle_next
09:46 python: stdout/stderr (slack):     self.handlers[function_name](j, self, team, channel, metadata)
09:46 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 2738, in handle_conversationsreplies
09:46 python: stdout/stderr (slack):     process_message(message, eventrouter, team, channel, metadata)
09:46 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 2872, in process_message
09:46 python: stdout/stderr (slack):     subtype_functions[subtype](message_json, eventrouter, team, channel, history_message)
09:46 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 2941, in subprocess_thread_message
09:46 python: stdout/stderr (slack):     channel.store_message(message, team)
09:46 python: stdout/stderr (slack): AttributeError: 'SlackThreadChannel' object has no attribute 'store_message'
```

I bisected it to this commit 6238505ebd5665e53edd94b7a12e4a2e67e9b9e9 (the one before works), it's still reproducible on current master 334b04798a51363

Curiously if I /close it and redo `/thread id` then 1 of the message appears, but nothing else. If I repeat /close and /thread then a duplicate message appears.

Actual:
![2020-03-13-095211_1032x105_scrot](https://user-images.githubusercontent.com/81471/76605207-5f3df700-6510-11ea-85d3-adc32653cf29.png)

Expected:
![2020-03-13-093812_1667x442_scrot](https://user-images.githubusercontent.com/81471/76605225-66fd9b80-6510-11ea-9897-ba7afde631d3.png)

This might be related, when I do /slack rehistory in that broken thread I get a different error:

```
11:12 =!= python: error in function "slack_command_cb"
11:13 python: stdout/stderr (slack): Traceback (most recent call last):
11:13 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 158, in wrapper
11:13 python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
11:13 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 4069, in slack_command_cb
11:13 python: stdout/stderr (slack):     return cmd(data, current_buffer, cmd_args)
11:13 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 147, in wrapper
11:13 python: stdout/stderr (slack):     return f(data, current_buffer, *args, **kwargs)
11:13 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 158, in wrapper
11:13 python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
11:13 python: stdout/stderr (slack):   File "/home/flugsio/.weechat/python/autoload/wee_slack.py", line 4041, in command_rehistory
11:13 python: stdout/stderr (slack):     channel.clear_messages()
11:13 python: stdout/stderr (slack): AttributeError: 'SlackThreadChannel' object has no attribute 'clear_messages'
11:13 =!= python: error in function "slack_command_cb"
```

**Comment by trygveaa** [comment]
> This might be related, when I do /slack rehistory in that broken thread I get a different error

This is not related, it's like that in other threads as well. We don't support rehistory in threads, so It has always been like this. Though, we should either implement support for it, or print a message saying it's not supported.
